version: '3.7'

services:
  app:
    build: .
    container_name: node
    restart: always
    env_file:
      - .env
    volumes:
      - .:/usr/app
    depends_on:
      - db
    links:
      - db
    ports:
      - '${APP_PORT}:${APP_PORT}'
    command: npm start
  db:
    image: mongo:latest
    container_name: db
    restart: always
    env_file:
      - .env
    ports:
      - '${DB_PORT}:27017'
    volumes:
      - dbdata-volume:/data/db
    environment:
      MONGO_INITDB_USERNAME: ${DB_USERNAME}
      MONGO_INITDB_PASSWORD: ${DB_PASSWORD}
      MONGO_INITDB_DATABASE: ${DB_DATABASE}

volumes:
  dbdata-volume: